# -*- coding: utf-8 -*-
"""DataExplore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ul5Rkia1sLpNTPXGSIwbjjkHhA5NdxwM
"""

import pandas as pd
df=pd.read_csv("/content/Sales Dataset.csv")
print('Display 10 rows of first')
print(df.head(10))
print('Display 10 rows of last')
print(df.tail(10))

import pandas as pd
df=pd.read_csv("/content/Sales Dataset.csv")
print ('displaying the info of the data')
print(df.info())

"""Describe() Method"""

import pandas as pd
data={
    "name":['ram','shyam','ghanshyam','dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,33,28,33,35,30,23],
    "salary":[50000,40000,35000,56000,25000,38000,45000,57000],
    "performance score":[85,90,78,92,88,95,80,89]

}

df=pd.DataFrame(data)
print("sample dataframe")
print(df)
print('discriptive statistics')
print(df.describe())

"""SHAPE AND COLUMNS"""

import pandas as pd
data={
    "name":['ram','shyam','ghanshyam','dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,33,28,33,35,30,23],
    "salary":[50000,40000,35000,56000,25000,38000,45000,57000],
    "performance score":[85,90,78,92,88,95,80,89]

}
df=pd.DataFrame(data)
print(df)
print(f'shape:{df.shape}')
print(f'column names:{df.columns}')

