# -*- coding: utf-8 -*-
"""handlingMisssingData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKDRDzsdIIMyLZepySXxL-IgIQQ3sVe8

HANDLING MISSING DATA

IS NULL(): to know missing values
1.nan
2.none
"""

import pandas as pd
data={
    "name":['ram','shyam',None,'dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,None,28,33,35,30,23],
    "salary":[50000,40000,None,56000,25000,38000,45000,57000],
    "performance score":[85,90,None,92,88,95,80,89]

}
df=pd.DataFrame(data)
print(df)

df=pd.DataFrame(data)
print(df)
print(df.isnull())
print(df.isnull().sum())

"""dropna():to drop the missing value"""

import pandas as pd
data={
    "name":['ram','shyam',None,'dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,None,28,33,35,30,23],
    "salary":[50000,40000,None,56000,25000,38000,45000,57000],
    "performance score":[85,90,None,92,88,95,80,89]

}
df=pd.DataFrame(data)
print(df)


df.dropna(inplace=True)
print(df)

"""fillna():to fillthe missing values"""

import pandas as pd
data={
    "name":['ram','shyam',None,'dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,None,28,33,35,30,23],
    "salary":[50000,40000,None,56000,25000,38000,45000,57000],
    "performance score":[85,90,None,92,88,95,80,89]

}
df=pd.DataFrame(data)
print(df)
#filling missing value with 0
df.fillna(0,inplace=True)
print(df)

#filling with conditional value
df['age'].fillna(df['age'].mean(),inplace =True)
df['salary'].fillna(df['salary'].mean(),inplace =True)
print(df)

"""interpolation() : to fill the data with estimate value based on other data"""

import pandas as pd
data={
    "time":[1,2,3,4,5],
    "value":[10,None,30,None,50]
}
df=pd.DataFrame(data)
print('before interpolation')
print(df)
df['value']=df['value'].interpolate(method='linear')
print('after interpolate')
print(df)