# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ee0yz6RdAIaHd_W8qgfQHUQ_j5iD39KC
"""

!pip install --upgrade pandas

import kagglehub

# Download latest version
path = kagglehub.dataset_download("chaitu20/ipl-dataset2008-2025")

print("Path to dataset files:", path)

import pandas as pd
#read data from CSV file into a dataframe
df=pd.read_csv("/Sales Dataset.csv",encoding="latin-1")
print(df)

import pandas as pd
#read data from excel file into a dataframe
df=pd.read_excel("/Historicalinvesttemp.xlsx")
print(df)

#to save files in pandas
import pandas as pd
data={
    "name":['ram','shyam','hari'],
    "age":[10,20,30],
    "city":['nagpur','mumbai','delhi']

}

df=pd.DataFrame(data)
print(df)
df.to_csv("output.csv")
df.to_csv("output.csv",index=false)