# -*- coding: utf-8 -*-
"""selecting and filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekpg1y-Un8JfW3T9lsY0F5ba0vkijs-G

SELECTING AND FILTERRING:

selecting column and columns:
"""

import pandas as pd
data={
    "name":['ram','shyam','ghanshyam','dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,33,28,33,35,30,23],
    "salary":[50000,40000,35000,56000,25000,38000,45000,57000],
    "performance score":[85,90,78,92,88,95,80,89]

}
df=pd.DataFrame(data)
#display the data frame
print("sample dataframe")
print("df")
print("Names(Single column return series)")
name=df["name"]

#selecting multiple columns
subset = df[["name", "salary"]]
print('\nsubset with name and salary')
print(subset)

"""filtering rows"""

import pandas as pd
data={
    "name":['ram','shyam','ghanshyam','dhanshyam','aditi','jagdish','raj','simran'],
    "age":[22,25,33,28,33,35,30,23],
    "salary":[50000,40000,35000,56000,25000,38000,45000,57000],
    "performance score":[85,90,78,92,88,95,80,89]

}
df=pd.DataFrame(data)
#filtering rows based on single condition
high_salary=df[df['salary']>50000]
print('employees salary > 50000')
print(high_salary)

#filtering rows salary>50k & age>30
filtered = df[(df['age']>30) & (df['salary']>50000)]
print(f'employees list age>30 + salary>50000')
print(filtered)

#using OR condition
filtered = df[(df['age']>30) & (df['performance score']>85)]
print(f'employees oder than 35 OR performance score >85')
print(filtered)