# -*- coding: utf-8 -*-
"""Sorting Aggregating&Grouping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLI--SWzubN0kRHeqe2w5vdx-5S2_XUS

SORING AND AGGREGATION & GROUPING

1.Sorting
"""

#sorting data in 1 column using sort_values()method
#syntax:df.sort_values(by="column_name",true/false,inplace=true)
import pandas as pd
data={
    "name":['arun','varun','karun'],
    "age":[22,38,34],
    "salary":[15000,20000,25000]

}
df=pd.DataFrame(data)
df.sort_values(by="age",ascending=False,inplace=True)
print('sorted age by descending order')
print(df)

#SORTING MULTIPLE COLUMNS
df=pd.DataFrame(data)
df.sort_values(by=["age","salary"],ascending=[True,True],inplace=True)
print('sorted age by descending order')
print(df)

"""2.aggregation(): provides numerical summry of the data"""

import pandas as pd
data={
    "name":['arun','varun','karun'],
    "age":[22,38,34],
    "salary":[15000,20000,25000]

}
df=pd.DataFrame(data)
avg_salary=df['salary'].mean()
sum_salary=df['salary'].sum()
max_salary=df['salary'].max()
min_salary=df['salary'].min()
print('average salary:',avg_salary)
print('sum of salary:',sum_salary)
print('maximum salary:',max_salary)
print('minimum salary:',min_salary)

"""3.GROUPING"""

import pandas as pd
data={
    "name":['arun','varun','karun','narun','marun'],
    "age":[22,38,34,23,30],
    "salary":[15000,20000,25000,30000,35000]

}
df=pd.DataFrame(data)
#grouping single column
grouped=df.groupby("age")["salary"].sum()
print(grouped)

#grouping multiple column
grouped=df.groupby(["age","name"])["salary"].sum()
print(grouped)

